stages:
  - check-and-create-mr
  - lint
  - test
  - build
  - e2e

variables:
  CI_LINTER_IMG: "mtr.devops.telekom.de/osc/common/pipeline-community/osc-gitlab-runner-linter:alpine-latest-0.9"
  GO_BUILD_IMG: "mtr.devops.telekom.de/osc/onmetal/container-images/go:go-1.25.0-alpine-3.22.1"
  SYNCHRONIZATION_GITLAB_IMAGE: mtr.devops.telekom.de/osc/upstream/synchronization/gitlab:v5.1.0-alpine

default:
  tags:
    - docker
    - pes
    - osc
  retry:
    max: 2
    when:
      - runner_system_failure
      - job_execution_timeout

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_PIPELINE_SOURCE == 'schedule'
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\..*/

# Common template to run jobs on changes in go files
.run-on-go-change:
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      changes:
        compare_to: 'osc/main'
        paths:
          - '**/*.go'
          - 'go.mod'
          - 'go.sum'

file-lint:
  stage: lint
  needs: []
  variables:
    FILES_LINT_CONFIG: './.linter-config/file-lint.conf'
  image: "${CI_LINTER_IMG}"
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      changes:
        compare_to: 'osc/main'
        paths:
          - "**/*"  # To ensure it won't run on empty commits
  script:
    - if [[ ${PIPELINE_DEBUG} == 1 ]]; then debug_flag="-x"; fi
    - if [[ -f "${FILES_LINT_CONFIG}" ]]; then cfg="--config ${FILES_LINT_CONFIG}"; fi
    - echo "${cfg}"
    - bash ${debug_flag} file-empty ${cfg} --path .
    - bash ${debug_flag} file-cr ${cfg} --path .
    - bash ${debug_flag} file-crlf ${cfg} --path .
    - bash ${debug_flag} file-nullbyte ${cfg} --path .
    - bash ${debug_flag} file-trailing-single-newline ${cfg} --path .
    - bash ${debug_flag} file-trailing-space ${cfg} --path .
    - bash ${debug_flag} file-utf8 ${cfg} --path .
    - bash ${debug_flag} file-utf8-bom ${cfg} --path .

yaml-lint:
  stage: lint
  needs: []
  variables:
    YAML_LINT_CONFIG: './.linter-config/yamllint.yaml'
  image: "${CI_LINTER_IMG}"
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      changes:
        compare_to: 'osc/main'
        paths:
          - "**/*.yaml"
          - "**/*.yml"
  script:
    - |
      if [[ -f "${YAML_LINT_CONFIG}" ]]; then
        cfg="-c ${YAML_LINT_CONFIG}"
      fi
      yamllint -f colored ${cfg} . && echo "Linting was successful."

markdown-lint:
  stage: lint
  needs: []
  variables:
    MARKDOWN_LINT_CONFIG: './.linter-config/mdlrc'
    MARKDOWN_LINT_IGNORE_CONFIG: "./.linter-config/.markdownlintignore"
  image: "${CI_LINTER_IMG}"
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      changes:
        compare_to: 'osc/main'
        paths:
          - "**/*.md"
          - ".linter-config/mdlrc"
          - ".linter-config/.markdownlintignore"
  script:
    - |
      # copy markdown ignore config if exists
      if [[ -f "${MARKDOWN_LINT_IGNORE_CONFIG}" ]]; then
        cp "${MARKDOWN_LINT_IGNORE_CONFIG}" .
      fi
      if [[ -f "${MARKDOWN_LINT_CONFIG}" ]]; then
        cfg="--config ${MARKDOWN_LINT_CONFIG}"
      fi
      { find -iname '*.md' -type f \
        | xargs markdownlint ${cfg}; } && echo "Linting was successful."

shell-lint:
  stage: lint
  needs: []
  image:
    name: "mtr.devops.telekom.de/osc/onmetal/container-images/shellcheck:0.10.0-alpine-3.21.2"
    entrypoint:
      - /bin/ash
      - -c
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      changes:
        compare_to: 'osc/main'
        paths:
          - "**/*.sh"
  variables:
    SHELL_LINT_EXCLUDES: .linter-config/shellcheck-excludes
  script:
    - |
      set -euo pipefail

      # find all shell scripts
      filelist=$(find . -iname '*.sh' -type f)

      echo -e "[INFO]: Files to lint: ${filelist}"

      if [[ -f "${SHELL_LINT_EXCLUDES}" ]]; then
        # read file, remove comments, and empty lines
        # return an empty string to mask grep's return value
        excludes=$(grep -v "^#" "${SHELL_LINT_EXCLUDES}" | grep -v '^[ \t]*$')
      else
        excludes=""
      fi

      echo -e "[INFO]: Exclude list: ${excludes}"

      # filter excludes from filelist
      if [[ -z "${excludes}" ]]; then
        echo "[INFO]: No .sh files excluded."
      else
        for exclude in ${excludes}; do
          filelist=$(echo "${filelist}" | grep -v "${exclude}")
        done
      fi

      if [[ -z "${filelist}" ]]; then
        echo "[INFO]: Nothing for linting."
        exit 0
      fi

      echo -e "[INFO]: Filtered list of files: ${filelist}"

      echo "${filelist}" | xargs shellcheck --rcfile .linter-config/shellcheckrc
      echo "[INFO]: Linting was successful."

go-lint:
  extends: .run-on-go-change
  stage: lint
  needs: []
  image:
    name: "${GO_BUILD_IMG}"
    entrypoint: ["/bin/ash", "-c"]
  script:
    - make lint

unit-tests:
  extends: .run-on-go-change
  stage: test
  image:
    name: "${GO_BUILD_IMG}"
    entrypoint: ["/bin/ash", "-c"]
  script:
    - make test

e2e-tests:
  stage: e2e
  tags:
    - infra-development
    - libvirt
  retry:
    max: 2
    when:
      - runner_system_failure
      - job_execution_timeout
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      changes:
        compare_to: 'osc/main'
        paths:
          - '**/*.go'
          - 'go.mod'
          - 'go.sum'
          - '**/hack/osc-pipeline-setup-e2e-env.sh'
  variables:
    TEST_REPORT_DIR: "e2e-test-reports"
  script:
    - bash ./hack/osc-pipeline-setup-e2e-env.sh
    - |
      set -e
      mkdir -p "${TEST_REPORT_DIR}"

      export CEPH_MONITORS="[$(ceph config show osd.1 mon_host)]:6789"
      export CEPH_IMAGE="devpool/test-img"
      export CEPH_USERNAME="admin"
      export CEPH_USERKEY="$(ceph auth print-key client.admin)"

      go run github.com/onsi/ginkgo/v2/ginkgo run \
        --label-filter="integration" \
        --coverprofile=cover.out \
        --junit-report="${TEST_REPORT_DIR}/report.xml" \
        ./internal/server/...
  artifacts:
    untracked: false
    when: always
    access: all
    expire_in: "7 days"
    paths:
      - cover.out
      - "${TEST_REPORT_DIR}/report.xml"
    reports:
      junit: "${TEST_REPORT_DIR}/report.xml"

build:
  extends: .run-on-go-change
  stage: build
  image:
    name: "${GO_BUILD_IMG}"
    entrypoint: ["/bin/ash", "-c"]
  script:
    - make build-only

check-dependabot-commits:
  stage: check-and-create-mr
  image:
    name: $SYNCHRONIZATION_GITLAB_IMAGE
    entrypoint: [""]
  variables:
    PYTHON_GITLAB_CFG: "$GITLAB_CFG"
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
    AUTHOR_ID: 342908
    PROJECT_ID: 238349
    REVIEWER_IDS: "40056,26108,41270"
    GITLAB_TIMEOUT: 10
  script:
    - bash ./hack/osc-check-dependabot-commits.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule'
