name: Run integration tests

on:
  workflow_dispatch:
  push:
    branches:
      - enh/integration-tests
  pull_request:
    types: [labeled, synchronize, reopened]
    paths-ignore:
      - 'docs/**'

jobs:
  integration-tests:
    runs-on: ubuntu-22.04
    #if: contains(github.event.pull_request.labels.*.name, 'integration-tests')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends qemu-utils ca-certificates libvirt-clients libcephfs-dev librbd-dev librados-dev libc-bin gcc
          sudo update-ca-certificates
          sudo rm -rf /var/lib/apt/lists
          sudo kvm-ok
          sudo apt install qemu-kvm libvirt-daemon-system

      - name: Run go tests
        run: |
          make integration-tests 
          
          # Add more steps if necessary (e.g., configuring networking, creating VMs, etc.)
